"""Configuration of the installed Shinka runner; no custom search loop."""
import os
os.environ.update(SHINKA_LLM_TIMEOUT='100',SHINKA_LLM_MAX_RETRIES='1',SHINKA_OPENAI_MAX_RETRIES='0',SHINKA_LLM_BACKOFF_MAX_TRIES='1',SHINKA_LLM_BACKOFF_MAX_TIME='100')
from shinka.core import EvolutionConfig,ShinkaEvolveRunner
from shinka.database import DatabaseConfig
from shinka.launch import LocalJobConfig

task='''Evolve a DATA-ONLY Python dictionary recipe for packing 119 equal spheres in a 6D unit ball. Never produce executable statements, functions, imports or code. Keep the EVOLVE block markers. The fixed evaluator uses ast.literal_eval and rejects everything except six fields: method shell or full; noise 0..0.02; beta 100..1000000; target_gain 1e-9..1e-3; maxiter integer 1..500; seed integer 0..2147483647. It evaluates 8 seeded trials per proposal. shell optimizes normalized boundary directions with log-sum-exp maximum dot product using L-BFGS-B, then rescales. full allows all centers including origin to move and minimizes squared overlap/wall violations at baseline+target_gain using analytic gradients and L-BFGS-B, then measures feasible radius. Current radius 0.3099639332166260, exact rational validity required, winner must exceed it by 1e-8. Previous shell beta10000 multistarts failed to improve. Choose a mechanism and numeric parameters to escape that plateau. Return the complete dictionary in the required full-rewrite format. Do not change the evaluator, constraints or budget.'''
evo=EvolutionConfig(task_sys_msg=task,init_program_path='initial.py',results_dir='results',num_generations=6,patch_types=['full'],patch_type_probs=[1.0],max_patch_resamples=1,max_patch_attempts=1,llm_models=['local/packing-cell@'+os.environ['CELL_API_URL']],llm_dynamic_selection=None,llm_kwargs={'temperatures':[1.0],'max_tokens':8192},embedding_model=None,meta_rec_interval=None,max_novelty_attempts=1,evolve_prompts=False,proposal_buffer_max=1,proposal_target_hard_cap=1)
ShinkaEvolveRunner(evo_config=evo,job_config=LocalJobConfig(eval_program_path='evaluate.py',time='00:00:50',numeric_threads_per_job=1),db_config=DatabaseConfig(),max_evaluation_jobs=1,max_proposal_jobs=1,max_db_workers=1,verbose=False,debug=False).run()
